# Generated by Django 4.2.5 on 2023-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
